[workspace]
channels = ["conda-forge"]
name = "feynhiggs-build"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]
download = """
rm -f FeynHiggs-2.19.0.tar.gz && \
rm -rf FeynHiggs-2.19.0 && \
curl -skLO https://wwwth.mpp.mpg.de/members/heinemey/feynhiggs/newversion/FeynHiggs-2.19.0.tar.gz && \
tar -xzf FeynHiggs-2.19.0.tar.gz
"""

build = """
cd FeynHiggs-2.19.0 && \
./configure --prefix=$CONDA_PREFIX --debug && \
make clean && \
make && \
make install && \
mv $CONDA_PREFIX/lib64/libFH.a $CONDA_PREFIX/lib64/
"""

cmake-build = """
cmake -DCMAKE_INSTALL_PREFIX="$CONDA_PREFIX" -S . -B build && \
cmake build -LH && \
cmake --build build --clean-first --parallel "$(nproc --ignore=4)" &&\
cmake --install build
"""

test = """
FeynHiggs FeynHiggs-2.19.0/example/SLHA/TestEXTPAR.spc
"""

cmake-test = """
FeynHiggs ./example/SLHA/TestEXTPAR.spc &> TestEXTPAR.out
"""

[tasks.start]
depends-on = ["download", "build"]


[dependencies]
cxx-compiler = ">=1.11.0,<2"
fortran-compiler = ">=1.11.0,<2"
cmake = ">=4.1.1,<5"
make = ">=4.4.1,<5"
curl = ">=8.14.1,<9"
sed = ">=4.9,<5"
gawk = ">=5.3.1,<6"
tar = ">=1.35,<2"

# Linux gets gdb
[target.linux-64.dependencies]
gdb = ">=16.3,<17"

[target.linux-aarch64.dependencies]
gdb = ">=16.3,<17"

# macOS gets lldb
[target.osx-64.dependencies]
lldb = ">=21.1.0,<22"

[target.osx-arm64.dependencies]
lldb = ">=21.1.0,<22"
